language: python

python:
    - "2.7"
    - "3.5"

install:
    - npm install -g bower
    - pip install cookiecutter
    - cookiecutter . --no-input
    - cd superawesome
    - pip install -r requirements.txt

script:
    - ./run.py
