language: python

python: 
    - "2.7"
    - "3.5"

install:
    - npm install -g bower
    - pip install cookiecutter
    - cookiecutter . --no-input
    - pip install -r superawesome/requirements.txt

script:
    - ./superawesome/run.py
